# Generated by Django 5.2.9 on 2025-12-16 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='License Key')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='อีเมล์ลูกค้า')),
                ('machine_id', models.CharField(max_length=255, verbose_name='Machine ID')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('duration_days', models.IntegerField(verbose_name='ระยะเวลา (วัน)')),
                ('activated_at', models.DateTimeField(verbose_name='วันที่ Activate')),
                ('expires_at', models.DateTimeField(verbose_name='วันหมดอายุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานได้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อซอฟต์แวร์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'ซอฟต์แวร์',
                'verbose_name_plural': 'ซอฟต์แวร์ทั้งหมด',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate', 'Activate'), ('validate', 'Validate'), ('renew', 'Renew'), ('revoke', 'Revoke')], max_length=20, verbose_name='การกระทำ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='สำเร็จ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='ข้อความ Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='license.license', verbose_name='License')),
            ],
            options={
                'verbose_name': 'Activation Log',
                'verbose_name_plural': 'Activation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='license.softwarename', verbose_name='ซอฟต์แวร์'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key'], name='license_lic_license_182969_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['machine_id', 'mac_address'], name='license_lic_machine_d58bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expires_at'], name='license_lic_expires_d5ac89_idx'),
        ),
    ]
