# Generated by Django 5.2.8 on 2025-12-16 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="activated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="วันที่ Activate"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="วันหมดอายุ"),
        ),
    ]
