# Generated by Django 5.2.9 on 2025-12-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_alter_license_activated_at_alter_license_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarename',
            options={'ordering': ['name'], 'verbose_name': 'Software Name', 'verbose_name_plural': 'All Software'},
        ),
    ]
